// Auto-generated from migrations/*.sql — do not edit

export const MIGRATION_SQL: string[] = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    api_key TEXT UNIQUE,
    avatar_url TEXT,
    github_username TEXT,
    google_email TEXT,
    system_role TEXT NOT NULL DEFAULT 'user' CHECK (system_role IN ('user', 'admin', 'super_admin')),
    is_active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT,
    preferences TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS machines (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hostname TEXT NOT NULL,
    os TEXT,
    arch TEXT,
    last_seen TEXT DEFAULT (datetime('now')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, hostname)
)`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    repo_url TEXT,
    description TEXT,
    owner_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    team_id TEXT,
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, name)
)`,
  `CREATE TABLE IF NOT EXISTS thoughts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    machine_id TEXT REFERENCES machines(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    type TEXT NOT NULL DEFAULT 'note' CHECK (type IN ('note', 'idea', 'question', 'todo', 'insight')),
    content TEXT NOT NULL,
    context TEXT DEFAULT '{}',
    tags TEXT DEFAULT '[]',
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    ai_model TEXT,
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS decisions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    machine_id TEXT REFERENCES machines(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    context TEXT,
    options TEXT DEFAULT '[]',
    chosen TEXT,
    rationale TEXT,
    outcome TEXT,
    tags TEXT DEFAULT '[]',
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    ai_model TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS sentiment (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL CHECK (target_type IN ('tool', 'library', 'pattern', 'codebase', 'task', 'process')),
    target_name TEXT NOT NULL,
    feeling TEXT NOT NULL CHECK (feeling IN ('frustrated', 'confused', 'satisfied', 'excited', 'neutral', 'annoyed', 'impressed')),
    intensity INTEGER CHECK (intensity BETWEEN 1 AND 5),
    reason TEXT,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    ai_model TEXT,
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    machine_id TEXT REFERENCES machines(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    started_at TEXT DEFAULT (datetime('now')),
    ended_at TEXT,
    mood_start TEXT,
    mood_end TEXT,
    goals TEXT DEFAULT '[]',
    accomplishments TEXT DEFAULT '[]',
    blockers TEXT DEFAULT '[]',
    summary TEXT,
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    ai_model TEXT,
    metadata TEXT DEFAULT '{}'
)`,
  `CREATE TABLE IF NOT EXISTS tags (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    description TEXT,
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS connections (
    id TEXT PRIMARY KEY,
    source_type TEXT NOT NULL CHECK (source_type IN ('thought', 'decision', 'session')),
    source_id TEXT NOT NULL,
    target_type TEXT NOT NULL CHECK (target_type IN ('thought', 'decision', 'session')),
    target_id TEXT NOT NULL,
    relationship TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(source_type, source_id, target_type, target_id, relationship)
)`,
  `CREATE TABLE IF NOT EXISTS dx_events (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    machine_id TEXT REFERENCES machines(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('command', 'tool_use', 'completion', 'error')),
    command TEXT,
    duration_ms INTEGER,
    tokens_in INTEGER,
    tokens_out INTEGER,
    success INTEGER,
    error_message TEXT,
    ai_model TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS dx_feedback (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    suggestion_type TEXT NOT NULL CHECK (suggestion_type IN ('code', 'command', 'explanation')),
    suggestion_hash TEXT,
    accepted INTEGER NOT NULL,
    modified INTEGER DEFAULT 0,
    feedback TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS dx_patterns (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    pattern_type TEXT NOT NULL CHECK (pattern_type IN ('workflow', 'preference', 'habit')),
    pattern_name TEXT NOT NULL,
    description TEXT,
    confidence REAL CHECK (confidence BETWEEN 0 AND 1),
    occurrences INTEGER DEFAULT 1,
    last_seen TEXT DEFAULT (datetime('now')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, pattern_type, pattern_name)
)`,
  `CREATE TABLE IF NOT EXISTS dx_costs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    date TEXT NOT NULL DEFAULT (date('now')),
    model TEXT NOT NULL,
    tokens_in INTEGER DEFAULT 0,
    tokens_out INTEGER DEFAULT 0,
    cost_usd REAL DEFAULT 0,
    request_count INTEGER DEFAULT 1,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, project_id, date, model)
)`,
  `CREATE TABLE IF NOT EXISTS oauth_accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL CHECK (provider IN ('github', 'google')),
    provider_user_id TEXT NOT NULL,
    provider_username TEXT,
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TEXT,
    profile_data TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(provider, provider_user_id)
)`,
  `CREATE TABLE IF NOT EXISTS auth_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    refresh_token_hash TEXT UNIQUE,
    expires_at TEXT NOT NULL,
    refresh_expires_at TEXT,
    user_agent TEXT,
    ip_address TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    last_used_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS teams (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    avatar_url TEXT,
    settings TEXT DEFAULT '{}',
    created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS team_members (
    id TEXT PRIMARY KEY,
    team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin', 'owner')),
    invited_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    joined_at TEXT DEFAULT (datetime('now')),
    UNIQUE(team_id, user_id)
)`,
  `CREATE TABLE IF NOT EXISTS project_members (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    team_id TEXT REFERENCES teams(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer', 'contributor', 'admin')),
    granted_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, user_id),
    UNIQUE(project_id, team_id)
)`,
  `CREATE TABLE IF NOT EXISTS team_invites (
    id TEXT PRIMARY KEY,
    team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin', 'owner')),
    token TEXT NOT NULL UNIQUE,
    invited_by TEXT REFERENCES users(id) ON DELETE SET NULL,
    expires_at TEXT NOT NULL,
    accepted_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(team_id, email)
)`,
  `CREATE TABLE IF NOT EXISTS github_repos (
    id TEXT PRIMARY KEY,
    project_id TEXT REFERENCES projects(id) ON DELETE CASCADE,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    full_name TEXT,
    html_url TEXT,
    default_branch TEXT DEFAULT 'main',
    sync_enabled INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(project_id, owner, name)
)`,
  `CREATE TABLE IF NOT EXISTS github_collaborators (
    id TEXT PRIMARY KEY,
    repo_id TEXT REFERENCES github_repos(id) ON DELETE CASCADE,
    github_user_id INTEGER NOT NULL,
    login TEXT NOT NULL,
    avatar_url TEXT,
    permissions TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(repo_id, github_user_id)
)`,
  `CREATE TABLE IF NOT EXISTS github_activity (
    id TEXT PRIMARY KEY,
    repo_id TEXT REFERENCES github_repos(id) ON DELETE CASCADE,
    activity_type TEXT NOT NULL CHECK (activity_type IN ('commit', 'pull_request', 'issue')),
    github_id TEXT NOT NULL,
    title TEXT,
    body TEXT,
    author_login TEXT,
    author_avatar TEXT,
    state TEXT,
    html_url TEXT,
    created_at TEXT NOT NULL,
    imported_at TEXT DEFAULT (datetime('now')),
    thought_id TEXT REFERENCES thoughts(id) ON DELETE SET NULL,
    UNIQUE(repo_id, activity_type, github_id)
)`,
  `CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    machine_id TEXT REFERENCES machines(id) ON DELETE SET NULL,
    ai_model TEXT,
    prompt_text TEXT NOT NULL,
    response_summary TEXT,
    turns INTEGER DEFAULT 1,
    prompt_tokens INTEGER,
    response_tokens INTEGER,
    goal_achieved INTEGER,
    context_sufficient INTEGER,
    quality_score REAL,
    tags TEXT DEFAULT '[]',
    metadata TEXT DEFAULT '{}',
    visibility TEXT DEFAULT 'private' CHECK (visibility IN ('private', 'team', 'public')),
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS decision_reviews (
    id TEXT PRIMARY KEY,
    decision_id TEXT NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    review_type TEXT NOT NULL DEFAULT 'follow_up' CHECK (review_type IN ('follow_up', 'retrospective', 'validation')),
    outcome_rating TEXT CHECK (outcome_rating IN ('positive', 'neutral', 'negative', 'too_early')),
    outcome_notes TEXT,
    lessons_learned TEXT,
    would_decide_same INTEGER,
    follow_up_days INTEGER,
    reviewed_at TEXT DEFAULT (datetime('now')),
    next_review_at TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS prompt_metrics (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
    total_turns INTEGER DEFAULT 0,
    avg_prompt_length INTEGER DEFAULT 0,
    context_provided_rate REAL DEFAULT 0,
    goal_achievement_rate REAL DEFAULT 0,
    first_try_success_rate REAL DEFAULT 0,
    backtrack_count INTEGER DEFAULT 0,
    clarification_requests INTEGER DEFAULT 0,
    total_tokens_used INTEGER DEFAULT 0,
    efficiency_score REAL,
    computed_at TEXT DEFAULT (datetime('now')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS event_triggers (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('session_end', 'decision_created', 'decision_review_due', 'weekly_summary', 'coaching_nudge', 'cost_alert')),
    trigger_config TEXT NOT NULL DEFAULT '{}',
    enabled INTEGER DEFAULT 1,
    last_fired_at TEXT,
    next_fire_at TEXT,
    fire_count INTEGER DEFAULT 0,
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS scoring_rubrics (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    category TEXT NOT NULL CHECK (category IN ('productivity', 'sentiment', 'flow', 'prompt_quality', 'decision_quality')),
    weights TEXT NOT NULL,
    thresholds TEXT NOT NULL DEFAULT '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}',
    is_default INTEGER DEFAULT 0,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE TABLE IF NOT EXISTS session_scores (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    productivity_score REAL NOT NULL DEFAULT 0,
    sentiment_score REAL NOT NULL DEFAULT 0,
    flow_score REAL NOT NULL DEFAULT 0,
    overall_score REAL NOT NULL DEFAULT 0,
    breakdown TEXT NOT NULL DEFAULT '{}',
    coaching_insights TEXT,
    what_went_well TEXT DEFAULT '[]',
    areas_for_improvement TEXT DEFAULT '[]',
    scored_at TEXT NOT NULL DEFAULT (datetime('now')),
    ai_model TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  `CREATE INDEX IF NOT EXISTS users_email_idx ON users(email)`,
  `CREATE INDEX IF NOT EXISTS users_api_key_idx ON users(api_key)`,
  `CREATE INDEX IF NOT EXISTS machines_user_idx ON machines(user_id)`,
  `CREATE INDEX IF NOT EXISTS thoughts_user_created_idx ON thoughts(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS thoughts_ai_model_idx ON thoughts(ai_model)`,
  `CREATE INDEX IF NOT EXISTS thoughts_type_idx ON thoughts(type)`,
  `CREATE INDEX IF NOT EXISTS thoughts_project_idx ON thoughts(project_id)`,
  `CREATE INDEX IF NOT EXISTS decisions_user_created_idx ON decisions(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS decisions_ai_model_idx ON decisions(ai_model)`,
  `CREATE INDEX IF NOT EXISTS decisions_project_idx ON decisions(project_id)`,
  `CREATE INDEX IF NOT EXISTS sentiment_ai_model_idx ON sentiment(ai_model)`,
  `CREATE INDEX IF NOT EXISTS sentiment_user_created_idx ON sentiment(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS sessions_user_created_idx ON sessions(user_id, started_at DESC)`,
  `CREATE INDEX IF NOT EXISTS sessions_ai_model_idx ON sessions(ai_model)`,
  `CREATE INDEX IF NOT EXISTS sessions_user_ended_idx ON sessions(user_id, ended_at)`,
  `CREATE INDEX IF NOT EXISTS dx_events_user_created_idx ON dx_events(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS dx_events_ai_model_idx ON dx_events(ai_model)`,
  `CREATE INDEX IF NOT EXISTS dx_costs_user_date_idx ON dx_costs(user_id, date DESC)`,
  `CREATE INDEX IF NOT EXISTS oauth_accounts_user_idx ON oauth_accounts(user_id)`,
  `CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions(user_id)`,
  `CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions(expires_at)`,
  `CREATE INDEX IF NOT EXISTS teams_slug_idx ON teams(slug)`,
  `CREATE INDEX IF NOT EXISTS team_members_user_idx ON team_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS team_members_team_idx ON team_members(team_id)`,
  `CREATE INDEX IF NOT EXISTS project_members_project_idx ON project_members(project_id)`,
  `CREATE INDEX IF NOT EXISTS project_members_user_idx ON project_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS project_members_team_idx ON project_members(team_id)`,
  `CREATE INDEX IF NOT EXISTS team_invites_token_idx ON team_invites(token)`,
  `CREATE INDEX IF NOT EXISTS team_invites_email_idx ON team_invites(email)`,
  `CREATE INDEX IF NOT EXISTS idx_github_repos_project ON github_repos(project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_github_activity_repo ON github_activity(repo_id)`,
  `CREATE INDEX IF NOT EXISTS idx_github_activity_type ON github_activity(activity_type)`,
  `CREATE INDEX IF NOT EXISTS idx_github_activity_created ON github_activity(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_session ON conversations(session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_created ON conversations(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_decision_reviews_decision ON decision_reviews(decision_id)`,
  `CREATE INDEX IF NOT EXISTS idx_decision_reviews_user ON decision_reviews(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_decision_reviews_next ON decision_reviews(next_review_at)`,
  `CREATE INDEX IF NOT EXISTS idx_prompt_metrics_user ON prompt_metrics(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_prompt_metrics_session ON prompt_metrics(session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_prompt_metrics_computed ON prompt_metrics(computed_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_event_triggers_user ON event_triggers(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_event_triggers_next ON event_triggers(next_fire_at)`,
  `CREATE INDEX IF NOT EXISTS idx_event_triggers_type ON event_triggers(event_type)`,
  `CREATE INDEX IF NOT EXISTS session_scores_session_idx ON session_scores(session_id)`,
  `CREATE INDEX IF NOT EXISTS session_scores_user_scored_idx ON session_scores(user_id, scored_at DESC)`,
  `INSERT OR IGNORE INTO scoring_rubrics (id, name, category, description, weights, thresholds, is_default) VALUES
('sr-productivity', 'default_productivity', 'productivity',
 'Measures goal achievement, decisions made, and insights generated',
 '{"goals_achieved_weight": 0.4, "decisions_made_weight": 0.2, "insights_generated_weight": 0.2, "blockers_resolved_weight": 0.2}',
 '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}', 1),
('sr-sentiment', 'default_sentiment', 'sentiment',
 'Measures emotional trajectory during session',
 '{"mood_improvement_weight": 0.3, "positive_sentiments_weight": 0.3, "frustration_absence_weight": 0.2, "satisfaction_weight": 0.2}',
 '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}', 1),
('sr-flow', 'default_flow', 'flow',
 'Measures uninterrupted productive flow',
 '{"success_rate_weight": 0.3, "error_absence_weight": 0.2, "blocker_absence_weight": 0.2, "session_duration_weight": 0.15, "focus_continuity_weight": 0.15}',
 '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}', 1),
('sr-prompt', 'default_prompt_quality', 'prompt_quality',
 'Measures effectiveness of AI prompting',
 '{"context_sufficiency_weight": 0.3, "first_try_success_weight": 0.25, "turns_efficiency_weight": 0.25, "goal_clarity_weight": 0.2}',
 '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}', 1),
('sr-decision', 'default_decision_quality', 'decision_quality',
 'Measures decision-making effectiveness',
 '{"options_considered_weight": 0.2, "rationale_depth_weight": 0.3, "outcome_tracking_weight": 0.25, "accuracy_rate_weight": 0.25}',
 '{"excellent": 80, "good": 60, "fair": 40, "poor": 0}', 1)`,
  `CREATE TABLE api_keys (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  UNIQUE(user_id, name)
)`,
  `CREATE INDEX api_keys_hash_idx ON api_keys(key_hash)`,
  `CREATE INDEX api_keys_user_idx ON api_keys(user_id)`,
  `ALTER TABLE thoughts ADD COLUMN deleted_at TEXT`,
  `ALTER TABLE decisions ADD COLUMN deleted_at TEXT`,
  `CREATE INDEX IF NOT EXISTS idx_thoughts_deleted_at ON thoughts(deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_decisions_deleted_at ON decisions(deleted_at)`,
  `CREATE TABLE IF NOT EXISTS handoffs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    from_project TEXT,
    to_project TEXT NOT NULL,
    handoff_type TEXT NOT NULL DEFAULT 'context'
        CHECK (handoff_type IN ('context', 'decision', 'blocker', 'task')),
    priority TEXT NOT NULL DEFAULT 'medium'
        CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    message TEXT NOT NULL,
    metadata TEXT DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'claimed', 'resolved')),
    claimed_at TEXT,
    claim_note TEXT,
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE INDEX IF NOT EXISTS idx_handoffs_user_status ON handoffs(user_id, status, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_handoffs_to_project ON handoffs(user_id, to_project, status)`,
  `ALTER TABLE api_keys ADD COLUMN scope TEXT NOT NULL DEFAULT 'write' CHECK (scope IN ('read', 'write', 'admin'))`,
  `ALTER TABLE api_keys ADD COLUMN expires_at TEXT`,
  `ALTER TABLE thoughts ADD COLUMN access_count INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE thoughts ADD COLUMN last_accessed_at TEXT`,
  `ALTER TABLE decisions ADD COLUMN access_count INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE decisions ADD COLUMN last_accessed_at TEXT`,
  `ALTER TABLE thoughts ADD COLUMN strength REAL NOT NULL DEFAULT 1.0`,
  `ALTER TABLE decisions ADD COLUMN strength REAL NOT NULL DEFAULT 1.0`,
  `CREATE TABLE IF NOT EXISTS oauth_clients (
    id TEXT PRIMARY KEY,
    client_secret_hash TEXT,
    client_name TEXT,
    redirect_uris TEXT NOT NULL,
    grant_types TEXT NOT NULL DEFAULT '["authorization_code"]',
    token_endpoint_auth_method TEXT NOT NULL DEFAULT 'client_secret_post',
    scope TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_authorization_codes (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    redirect_uri TEXT NOT NULL,
    scope TEXT,
    code_challenge TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL DEFAULT 'S256',
    resource TEXT,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_tokens (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    refresh_token_hash TEXT UNIQUE,
    scope TEXT,
    expires_at TEXT NOT NULL,
    refresh_expires_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    last_used_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS orchestrator_agents (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    provider TEXT,
    model TEXT,
    status TEXT NOT NULL DEFAULT 'idle'
        CHECK (status IN ('idle', 'busy', 'offline')),
    metadata TEXT DEFAULT '{}',
    last_seen_at TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, name)
)`,
  `CREATE INDEX IF NOT EXISTS idx_orchestrator_agents_user ON orchestrator_agents(user_id, status)`,
  `CREATE TABLE IF NOT EXISTS orchestrator_rooms (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    visibility TEXT DEFAULT 'private'
        CHECK (visibility IN ('private', 'team', 'public')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, name)
)`,
  `CREATE INDEX IF NOT EXISTS idx_orchestrator_rooms_user ON orchestrator_rooms(user_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS orchestrator_messages (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_id TEXT NOT NULL REFERENCES orchestrator_rooms(id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL DEFAULT 'user'
        CHECK (sender_type IN ('user', 'agent', 'system')),
    sender_name TEXT,
    agent_id TEXT REFERENCES orchestrator_agents(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
)`,
  `CREATE INDEX IF NOT EXISTS idx_orchestrator_messages_room ON orchestrator_messages(user_id, room_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS orchestrator_presence (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_id TEXT NOT NULL REFERENCES orchestrator_rooms(id) ON DELETE CASCADE,
    agent_id TEXT NOT NULL REFERENCES orchestrator_agents(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'online'
        CHECK (status IN ('online', 'idle', 'busy', 'offline')),
    last_seen_at TEXT DEFAULT (datetime('now')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(user_id, room_id, agent_id)
)`,
  `CREATE INDEX IF NOT EXISTS idx_orchestrator_presence_room ON orchestrator_presence(user_id, room_id, status)`,
]
